### ISSUE TITLE
Reuse port 3702 and ws-discovery service from firewalld

### ISSUE THREAD

**Issue by hgraeber** [christgau/wsdd#232]
Whay do wsdd and its firewall services use port 37020. Sure port 3702 is already assigned. But exactly for ws-discovery and not for some other unrelated protocol.

Calling  `getent services 3702/udp` results  in 
```
ws-discovery 3702/udp
```

And `firewall-cmd --info-service=ws-discovery-udp` in
```yaml
ws-discovery-udp
  ports: 3702/udp
  protocols: 
  source-ports: 
  modules: 
  destination: ipv4:239.255.255.250 ipv6:ff02::c
  includes: 
  helpers: 
```

So there is no need for using another port or your own firewalld service file. Instead the ones which are already present shall be reused.
